AllCops:
  TargetRubyVersion: 2.0

Metrics/LineLength:
  Max: 100
  Enabled: false

Style/Encoding:
  Description: 'Use UTF-8 as the source file encoding.'
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/SignalException:
  Description: 'Do not enforce use of fail when raising exceptions.'
  # Valid values are: semantic, only_raise and only_fail
  EnforcedStyle: only_raise

Style/SpecialGlobalVars:
  # auto "correct" adds gem requirement
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
